const content = [
    {
        "img": "./img/family.svg",
        "title": "Fin de la pobreza",
        "parrafo": "A nivel mundial, el número de personas que viven en situación de extrema pobreza disminuyó desde un 36 % en 1990 hasta un 10 % en 2015. No obstante, el ritmo al que se produce este cambio está disminuyendo, y la crisis de la COVID-19 pone en riesgo décadas de progreso en la lucha contra la pobreza. Una nueva investigación publicada por el Instituto Mundial de Investigaciones de Economía del Desarrollo de la Universidad de las Naciones Unidas advierte de que las consecuencias económicas de la pandemia mundial podrían incrementar la pobreza en todo el mundo hasta llegar a afectar a 500 millones de personas más, o lo que es lo mismo, a un 8 % más de la población total mundial. Esta sería la primera vez que la pobreza aumente en todo el mundo en 30 años, desde 1990.|| Más de 700 millones de personas, o el 10 % de la población mundial, aún vive en situación de extrema pobreza a día de hoy, con dificultades para satisfacer las necesidades más básicas, como la salud, la educación y el acceso a agua y saneamiento, por nombrar algunas. La mayoría de las personas que viven con menos de 1,90 dólares al día viven en el África subsahariana. En todo el mundo, los índices de pobreza en las áreas rurales son del 17,2 %; más del triple de los mismos índices para las áreas urbanas.||Para los que trabajan, su puesto de trabajo no les garantiza una vida digna. De hecho, el 8 % de los trabajadores de todo el mundo, y sus familias, vivían en situación de extrema pobreza en 2018. Uno de cada cinco niños vive en situación de extrema pobreza. Garantizar la protección social de todos los niños y otros grupos vulnerables resulta crucial para reducir la pobreza."
    },
    {
        "img": "./img/book.svg",
        "title": "Educación de Calidad",
        "parrafo": "La educación permite la movilidad socioeconómica ascendente y es clave para salir de la pobreza. Durante la última década, se consiguieron grandes avances a la hora de ampliar el acceso a la educación y las tasas de matriculación en las escuelas en todos los niveles, especialmente para las niñas. No obstante, alrededor de 260 millones de niños aún estaban fuera de la escuela en 2018; cerca de una quinta parte de la población mundial de ese grupo de edad. Además, más de la mitad de todos los niños y adolescentes de todo el mundo no están alcanzando los estándares mínimos de competencia en lectura y matemáticas.||En 2020, a medida que la pandemia de la COVID-19 se propagaba por todo el planeta, la mayor parte de los países anunciaron el cierre temporal de las escuelas, lo que afectó a más del 91 % de los estudiantes en todo el mundo. En abril de 2020, cerca de 1600 millones de niños y jóvenes estaban fuera de la escuela. Igualmente, cerca de 369 millones de niños que dependen de los comedores escolares tuvieron que buscar otras fuentes de nutrición diaria.||Nunca antes habían estado tantos niños fuera de la escuela al mismo tiempo, lo que altera su aprendizaje y cambia drásticamente sus vidas, especialmente las de los niños más vulnerables y marginados. La pandemia mundial tiene graves consecuencias que pueden poner en peligro los avances que tanto costaron conseguir a la hora de mejorar la educación a nivel mundial."
    },
    {
        "img": "./img/energy.svg",
        "title": "Energías sostenibles",
        "parrafo": "El mundo está avanzando hacia la consecución del Objetivo 7 con indicios alentadores de que la energía se está volviendo más sostenible y ampliamente disponible. El acceso a la electricidad en los países más pobres ha comenzado a acelerarse, la eficiencia energética continúa mejorando y la energía renovable está logrando resultados excelentes en el sector eléctrico.||A pesar de ello, es necesario prestar una mayor atención a las mejoras para el acceso a combustibles de cocina limpios y seguros, y a tecnologías para 3000 millones de personas, para expandir el uso de la energía renovable más allá del sector eléctrico e incrementar la electrificación en el África subsahariana.||El informe de progreso en materia de energía proporciona un registro mundial del progreso relativo al acceso a la energía, la eficiencia energética y la energía renovable. Evalúa el progreso conseguido por cada país en estos tres pilares y ofrece una panorámica del camino que nos queda por recorrer para conseguir las metas de los Objetivos de Desarrollo Sostenible 2030."
    },
    {
        "img": "./img/red-igualdades.svg",
        "title": "Reducción de las desigualdades",
        "parrafo": "La desigualdad dentro de los países y entre estos es un continuo motivo de preocupación. A pesar de la existencia de algunos indicios positivos hacia la reducción de la desigualdad en algunas dimensiones, como la reducción de la desigualdad de ingresos en algunos países y el estatus comercial preferente que beneficia a los países de bajos ingresos, la desigualdad aún continúa.||La COVID-19 ha intensificado las desigualdades existentes y ha afectado más que nadie a los pobres y las comunidades más vulnerables. Ha sacado a la luz las desigualdades económicas y las frágiles redes de seguridad social que hacen que las comunidades vulnerables tengan que sufrir las consecuencias de la crisis. Al mismo tiempo, las desigualdades sociales, políticas y económicas han amplificado los efectos de la pandemia.||En el frente económico, la pandemia de la COVID-19 ha aumentado significativamente el desempleo mundial y ha recortado drásticamente los ingresos de los trabajadores.||La COVID-19 también pone en riesgo los escasos avances que se han conseguido en materia de igualdad de género y derechos de las mujeres durante las últimas décadas. Prácticamente en todos los ámbitos, desde la salud hasta la economía, desde la seguridad hasta la protección social, los efectos de la COVID-19 han agravado la situación de las mujeres y las niñas simplemente como consecuencia de su sexo."
    },
    {
        "img": "./img/hambre_0.svg",
        "title": "Hambre Cero",
        "parrafo": "Tras décadas de una disminución constante, el número de personas que padecen hambre (medido por la prevalencia de desnutrición) comenzó a aumentar lentamente de nuevo en 2015. Las estimaciones actuales indican que cerca de 690 millones de personas en el mundo padecen hambre, es decir, el 8,9 por ciento de la población mundial, lo que supone un aumento de unos 10 millones de personas en un año y de unos 60 millones en cinco años.||El mundo no está bien encaminado para alcanzar el objetivo de hambre cero para 2030. Si continúan las tendencias recientes, el número de personas afectadas por el hambre superará los 840 millones de personas para 2030.||Según el Programa Mundial de Alimentos, alrededor de 135 millones de personas padecen hambre severa Disponible en inglés, debido principalmente a los conflictos causados por los seres humanos, el cambio climático y las recesiones económicas. La pandemia de COVID-19 podría duplicar ahora esa cifra y sumar unos 130 millones de personas más que estarían en riesgo de padecer hambre severa a finales de 2020.||Con más de 250 millones de personas que podrían encontrarse al borde de la hambruna Disponible en inglés, es necesario actuar rápidamente para proporcionar alimentos y ayuda humanitaria a las regiones que corren más riesgos."
    },
    {
        "img": "./img/igualdad.svg",
        "title": "Igualdad de género",
        "parrafo": "La igualdad de género no solo es un derecho humano fundamental, sino que es uno de los fundamentos esenciales para construir un mundo pacífico, próspero y sostenible.||A pesar de estos logros, todavía existen muchas dificultades: las leyes y las normas sociales discriminatorias continúan siendo generalizadas, las mujeres siguen estando infrarrepresentadas a todos los niveles de liderazgo político, y 1 de cada 5 mujeres y niñas de entre 15 y 49 años afirma haber sufrido violencia sexual o física a manos de una pareja íntima en un período de 12 meses.||Los efectos de la pandemia de la COVID-19 podrían revertir los escasos logros que se han alcanzado en materia de igualdad de género y derechos de las mujeres. El brote de coronavirus agrava las desigualdades existentes para las mujeres y niñas a nivel mundial; desde la salud y la economía, hasta la seguridad y la protección social.||Las mujeres desempeñan un papel desproporcionado en la respuesta al virus, incluso como trabajadoras sanitarias en primera línea y como cuidadoras en el hogar. El trabajo de cuidados no remunerado de las mujeres ha aumentado de manera significativa como consecuencia del cierre de las escuelas y el aumento de las necesidades de los ancianos. Las mujeres también se ven más afectadas por los efectos económicos de la COVID-19, ya que trabajan, de manera desproporcionada, en mercados laborales inseguros. Cerca del 60 % de las mujeres trabaja en la economía informal, lo que las expone aún más a caer en la pobreza."
    },
    {
        "img": "./img/empleo.svg",
        "title": "Empleo y crecimiento económico",
        "parrafo": "Un crecimiento económico inclusivo y sostenido puede impulsar el progreso, crear empleos decentes para todos y mejorar los estándares de vida.||La COVID-19 ha alterado miles de millones de vidas y ha puesto en peligro la economía mundial. El Fondo Monetario Internacional (FMI) prevé una recesión mundial tan mala o peor que la de 2009. A medida que se intensifica la pérdida de empleo, la Organización Internacional del Trabajo estima que cerca de la mitad de todos los trabajadores a nivel mundial se encuentra en riesgo de perder sus medios de subsistencia.||Incluso antes del brote de la COVID-19, era probable que uno de cada cinco países (en donde habitan miles de millones de personas que viven en situación de pobreza) vieran sus ingresos per cápita estancarse o reducirse en 2020. A día de hoy, las perturbaciones económicas y financieras derivadas de la COVID-19 (como las alteraciones en la producción industrial, la caída de los precios de los productos básicos, la volatilidad del mercado financiero y el aumento de la inseguridad) están desbaratando el ya de por sí tibio crecimiento económico y empeorando los riesgos acentuados de otros factores."
    },
    {
        "img": "./img/ciudades.svg",
        "title": "Ciudades y comunidades sostenibles",
        "parrafo": "El mundo cada vez está más urbanizado. Desde 2007, más de la mitad de la población mundial ha estado viviendo en ciudades, y se espera que dicha cantidad aumente hasta el 60 % para 2030.||Las ciudades y las áreas metropolitanas son centros neurálgicos del crecimiento económico, ya que contribuyen al 60 % aproximadamente del PIB mundial. Sin embargo, también representan alrededor del 70 % de las emisiones de carbono mundiales y más del 60 % del uso de recursos.||La rápida urbanización está dando como resultado un número creciente de habitantes en barrios pobres, infraestructuras y servicios inadecuados y sobrecargados (como la recogida de residuos y los sistemas de agua y saneamiento, carreteras y transporte), lo cual está empeorando la contaminación del aire y el crecimiento urbano incontrolado.||El impacto de la COVID-19 será más devastador en las zonas urbanas pobres y densamente pobladas, especialmente para el mil millón de personas que vive en asentamientos informales y en barrios marginales en todo el mundo, donde el hacinamiento también dificulta cumplir con las medidas recomendadas, como el distanciamiento social y el autoaislamiento.||El organismo de las Naciones Unidas para los alimentos, la FAO, advirtió de que el hambre y las muertes podrían aumentar de manera significativa en las zonas urbanas que no cuentan con medidas para garantizar que los residentes pobres y vulnerables tengan acceso a alimentos."
    },
    {
        "img": "./img/salud.svg",
        "title": "Buena salud",
        "parrafo": "Actualmente, el mundo se enfrenta a una crisis sanitaria mundial sin precedentes; la COVID-19 está propagando el sufrimiento humano, desestabilizando la economía mundial y cambiando drásticamente las vidas de miles de millones de personas en todo el mundo.||Antes de la pandemia, se consiguieron grandes avances en la mejora de la salud de millones de personas. En concreto, estos grandes avances se alcanzaron al aumentar la esperanza de vida y reducir algunas de las causas de muerte comunes asociadas con la mortalidad infantil y materna. Sin embargo, se necesitan más esfuerzos para erradicar por completo una gran variedad de enfermedades y abordar un gran número de problemas de salud, tanto constantes como emergentes. A través de una financiación más eficiente de los sistemas sanitarios, un mayor saneamiento e higiene, y un mayor acceso al personal médico, se podrán conseguir avances significativos a la hora de ayudar a salvar las vidas de millones de personas.||Las emergencias sanitarias, como la derivada de la COVID-19, suponen un riesgo mundial y han demostrado que la preparación es vital. El Programa de las Naciones Unidas para el Desarrollo señaló las grandes diferencias relativas a las capacidades de los países para lidiar con la crisis de la COVID-19 y recuperarse de ella. La pandemia constituye un punto de inflexión en lo referente a la preparación para las emergencias sanitarias y la inversión en servicios públicos vitales del siglo XXI."
    },
    {
        "img": "./img/agua.svg",
        "title": "Agua potable y saneamiento",
        "parrafo": "Si bien se ha conseguido progresar de manera sustancial a la hora de ampliar el acceso a agua potable y saneamiento, existen miles de millones de personas (principalmente en áreas rurales) que aún carecen de estos servicios básicos. En todo el mundo, una de cada tres personas no tiene acceso a agua potable salubre, dos de cada cinco personas no disponen de una instalación básica destinada a lavarse las manos con agua y jabón, y más de 673 millones de personas aún defecan al aire libre.||La pandemia de la COVID-19 ha puesto de manifiesto la importancia vital del saneamiento, la higiene y un acceso adecuado a agua limpia para prevenir y contener las enfermedades. La higiene de manos salva vidas. De acuerdo con la Organización Mundial de la Salud, el lavado de manos es una de las acciones más efectivas que se pueden llevar a cabo para reducir la propagación de patógenos y prevenir infecciones, incluido el virus de la COVID-19. Aun así, hay miles de millones de personas que carecen de acceso a agua salubre y saneamiento, y los fondos son insuficientes."
    },
    {
        "img": "./img/inovacion.svg",
        "title": "Innovación y estructura",
        "parrafo": "La industrialización inclusiva y sostenible, junto con la innovación y la infraestructura, pueden dar rienda suelta a las fuerzas económicas dinámicas y competitivas que generan el empleo y los ingresos. Estas desempeñan un papel clave a la hora de introducir y promover nuevas tecnologías, facilitar el comercio internacional y permitir el uso eficiente de los recursos.||Sin embargo, todavía queda un largo camino que recorrer para que el mundo pueda aprovechar al máximo este potencial. En especial, los países menos desarrollados necesitan acelerar el desarrollo de sus sectores manufactureros si desean conseguir la meta de 2030 y aumentar la inversión en investigación e innovación científicas.||El crecimiento del sector manufacturero a nivel mundial ha ido disminuyendo constantemente, incluso antes del brote de la pandemia de la COVID-19. La pandemia está afectando gravemente a las industrias manufactureras y está provocando alteraciones en las cadenas de valor mundiales y en el suministro de productos.||La innovación y el progreso tecnológico son claves para descubrir soluciones duraderas para los desafíos económicos y medioambientales, como el aumento de la eficiencia energética y de recursos. A nivel mundial, la inversión en investigación y desarrollo (I+D), como porcentaje del PIB, aumentó de un 1,5 % en el 2000 a un 1,7 % en el 2015, y continuó casi en el mismo nivel en el 2017. Sin embargo, en las regiones en desarrollo fue inferior al 1 %."
    },
    {
        "img": "./img/consumo_produccion_icono.svg",
        "title": "Consumo y producción sostenibles",
        "parrafo": "El consumo y la producción mundiales (fuerzas impulsoras de la economía mundial) dependen del uso del medio ambiente natural y de los recursos de una manera que continúa teniendo efectos destructivos sobre el planeta.||El progreso económico y social conseguido durante el último siglo ha estado acompañado de una degradación medioambiental que está poniendo en peligro los mismos sistemas de los que depende nuestro desarrollo futuro (y ciertamente, nuestra supervivencia).||La pandemia de la COVID-19 ofrece a los países la oportunidad de elaborar planes de recuperación que reviertan las tendencias actuales y cambien nuestros patrones de consumo y producción hacia un futuro más sostenible.||El consumo y la producción sostenibles consisten en hacer más y mejor con menos. También se trata de desvincular el crecimiento económico de la degradación medioambiental, aumentar la eficiencia de recursos y promover estilos de vida sostenibles.||El consumo y la producción sostenibles también pueden contribuir de manera sustancial a la mitigación de la pobreza y a la transición hacia economías verdes y con bajas emisiones de carbono."
    },
    {
        "img": "./img/accion_clima_icono.svg",
        "title": "Acción por el clima",
        "parrafo": "El 2019 fue el segundo año más caluroso de todos los tiempos y marcó el final de la década más calurosa (2010-2019) que se haya registrado jamás.||Los niveles de dióxido de carbono (CO2) y de otros gases de efecto invernadero en la atmósfera aumentaron hasta niveles récord en 2019.||El cambio climático está afectando a todos los países de todos los continentes. Está alterando las economías nacionales y afectando a distintas vidas. Los sistemas meteorológicos están cambiando, los niveles del mar están subiendo y los fenómenos meteorológicos son cada vez más extremos.||A pesar de que se estima que las emisiones de gases de efecto invernadero caigan alrededor de un 6 % en 2020 debido a las restricciones de movimiento y las recesiones económicas derivadas de la pandemia de la COVID-19, esta mejora es solo temporal. El cambio climático no se va a pausar. Una vez que la economía mundial comience a recuperarse de la pandemia, se espera que las emisiones vuelvan a niveles mayores.||Es necesario tomar medidas urgentes para abordar tanto la pandemia como la emergencia climática con el fin de salvar vidas y medios de subsistencia."
    },
    {
        "img": "./img/paz.svg",
        "title": "Paz y justicia",
        "parrafo": "Los conflictos, la inseguridad, las instituciones débiles y el acceso limitado a la justicia continúan suponiendo una grave amenaza para el desarrollo sostenible.||El número de personas que huyen de las guerras, las persecuciones y los conflictos superó los 70 millones en 2018, la cifra más alta registrada por la Oficina del Alto Comisionado de las Naciones Unidas para los Refugiados (ACNUR) en casi 70 años.||En 2019, las Naciones Unidas registraron 357 asesinatos y 30 desapariciones forzadas de defensores de los derechos humanos, periodistas y sindicalistas en 47 países.||Por otro lado, los nacimientos de alrededor de uno de cada cuatro niños en todo el mundo con menos de 5 años nunca se registran de manera oficial, lo que les priva de una prueba de identidad legal, que es crucial para la protección de sus derechos y para el acceso a la justicia y a los servicios sociales."
    },
    {
        "img": "./img/vida_submarina.svg",
        "title": "Vida submarina",
        "parrafo": "El océano impulsa los sistemas mundiales que hacen de la Tierra un lugar habitable para el ser humano. Nuestra lluvia, el agua potable, el tiempo, el clima, los litorales, gran parte de nuestra comida e incluso el oxígeno del aire que respiramos los proporciona y regula el mar.||Una gestión cuidadosa de este recurso mundial esencial es una característica clave de un futuro sostenible. No obstante, en la actualidad, existe un deterioro continuo de las aguas costeras debido a la contaminación y a la acidificación de los océanos que está teniendo un efecto adverso sobre el funcionamiento de los ecosistemas y la biodiversidad. Asimismo, también está teniendo un impacto perjudicial sobre las pesquerías de pequeña escala.||Proteger nuestros océanos debe seguir siendo una prioridad. La biodiversidad marina es vital para la salud de las personas y de nuestro planeta. Las áreas marinas protegidas se deben gestionar de manera efectiva, al igual que sus recursos, y se deben poner en marcha reglamentos que reduzcan la sobrepesca, la contaminación marina y la acidificación de los océanos."
    },
    {
        "img": "./img/alianza.svg",
        "title": "Alianza para el logro de los objetivos",
        "parrafo": "Los ODS solo se pueden conseguir con asociaciones mundiales sólidas y cooperación.||Para que un programa de desarrollo se cumpla satisfactoriamente, es necesario establecer asociaciones inclusivas (a nivel mundial, regional, nacional y local) sobre principios y valores, así como sobre una visión y unos objetivos compartidos que se centren primero en las personas y el planeta.||Muchos países requieren asistencia oficial para el desarrollo con el fin de fomentar el crecimiento y el comercio. Aun así, los niveles de ayuda están disminuyendo y los países donantes no han respetado su compromiso de aumentar la financiación para el desarrollo.||Debido a la pandemia de la COVID-19, se espera que la economía mundial se contraiga fuertemente, en un 3 %, en 2020, lo que constituiría su peor recesión desde la Gran Depresión.||Ahora más que nunca es necesaria una sólida cooperación internacional con el fin de garantizar que los países que poseen los medios para recuperarse de la pandemia reconstruyan mejor y consigan los Objetivos de Desarrollo Sostenible."
    },
    {
        "img": "./img/flora_fauna.svg",
        "title": "Flora y fauna terrestre",
        "parrafo": "El brote de la COVID-19 resalta la necesidad de abordar las amenazas a las que se enfrentan las especies silvestres y los ecosistemas.||En 2016, el Programa de las Naciones Unidas para el Medio Ambiente (PNUMA) alertó de que un aumento mundial de las epidemias zoonóticas era motivo de preocupación. En concreto, señaló que el 75 % de todas las enfermedades infecciosas nuevas en humanos son zoonóticas y que dichas enfermedades están estrechamente relacionadas con la salud de los ecosistemas.||«Con la COVID-19, el planeta ha enviado su mayor alerta hasta la fecha indicando que la humanidad debe cambiar», ha explicado la Directora Ejecutiva del PNUMA, Inger Andersen.||En Trabajar con el medio ambiente para proteger a las personas, el PNUMA detalla cómo «reconstruir mejor», mediante una base científica más sólida, políticas que contribuyan a un planeta más sano y más inversiones verdes."
    },
    
];